assert (~/^$/).matcher("a\n").find() == false
assert (~/^$/).matcher("\n").find() == true
assert (~/^$/).matcher("a").find() == false
assert (~/^$/).matcher("").find() == true
assert (~/^$/).matcher("\t\n").find() == false
assert (~/^$/).matcher("aaa\nbbb").find() == false
assert (~/\A\s*\z/).matcher("a\n").find() == false
assert (~/\A\s*\z/).matcher("\n").find() == true
assert (~/\A\s*\z/).matcher("a").find() == false
assert (~/\A\s*\z/).matcher("").find() == true
assert (~/\A\s*\z/).matcher("\t\n").find() == true
assert (~/\A\s*\z/).matcher("aaa\nbbb").find() == false
